// Agent context/session helper. Replies are generated by the CloudBase agent
// function; this module only prepares whitelisted user context and reads history.
const workoutRepo = require('./repositories/workout.js')
const planRepo = require('./repositories/plan.js')
const bodyRepo = require('./repositories/body.js')
const nutritionRepo = require('./repositories/nutrition.js')
const agentRepo = require('./repositories/agent.js')

const MAX_MESSAGES = 40

const DEFAULT_MESSAGES = [{
  role: 'assistant',
  content: '告诉我你的训练目标、每周可训练几天，以及有没有需要避开的动作。'
}]
const DEFAULT_DIET_MESSAGES = [{
  role: 'assistant',
  content: '告诉我你的饮食目标、忌口和每天大概几餐。我会给你一份可编辑的饮食方案。'
}]

function asArray(value) {
  return Array.isArray(value) ? value : []
}

function safeGet(collection, query) {
  return query(collection).get().then((res) => (res && res.data) || []).catch(() => [])
}

function buildContext() {
  return Promise.all([
    workoutRepo.listRecent(10).catch(() => []),
    planRepo.list(10).catch(() => []),
    bodyRepo.listAll().then((rows) => rows.slice().sort((a, b) => String(b.dateStr || '').localeCompare(String(a.dateStr || ''))).slice(0, 3)).catch(() => [])
  ]).then(([workouts, plans, body]) => ({
    recentWorkouts: workouts.map((item) => ({
      date: item.dateStr || '',
      title: item.title || '',
      exercises: asArray(item.exercises || item.items).slice(0, 12)
    })),
    existingPlans: plans.map((item) => ({
      name: item.name || '',
      items: asArray(item.items).slice(0, 12)
    })),
    bodyMetrics: body[0]
      ? { weight: body[0].weight, height: body[0].height, bodyFat: body[0].bodyFat }
      : null
  }))
}

function buildDietContext() {
  return Promise.all([
    nutritionRepo.listAll().then((rows) => rows.slice().sort((a, b) => String(b.dateStr || '').localeCompare(String(a.dateStr || ''))).slice(0, 30)).catch(() => []),
    nutritionRepo.latestPlan().then((row) => row ? [row] : []).catch(() => []),
    bodyRepo.listAll().then((rows) => rows.slice().sort((a, b) => String(b.dateStr || '').localeCompare(String(a.dateStr || ''))).slice(0, 3)).catch(() => [])
  ]).then(([logs, plans, body]) => ({
    recentMeals: logs.map((item) => ({
      dateStr: item.dateStr || '',
      mealType: item.mealType || 'other',
      calories: Number(item.calories) || 0,
      protein: Number(item.protein) || 0,
      carbs: Number(item.carbs) || 0,
      fat: Number(item.fat) || 0
    })),
    existingDietPlans: plans.map((item) => ({
      name: item.name || '',
      dailyTarget: item.dailyTarget || {},
      meals: Array.isArray(item.meals) ? item.meals.slice(0, 8) : []
    })),
    bodyMetrics: body[0]
      ? { weight: body[0].weight, height: body[0].height, bodyFat: body[0].bodyFat || body[0].fatPct }
      : null
  }))
}

function normalizeMessages(messages) {
  return asArray(messages)
    .filter((item) => item && (item.role === 'user' || item.role === 'assistant'))
    .map((item) => ({ role: item.role, content: String(item.content || '').slice(0, 1200) }))
    .slice(-MAX_MESSAGES)
}

function loadSession(sessionId) {
  if (!sessionId) return Promise.resolve(null)
  return agentRepo.getSession(sessionId)
    .then((res) => res && res.data ? res.data : null)
    .catch(() => null)
}

module.exports = {
  DEFAULT_MESSAGES,
  DEFAULT_DIET_MESSAGES,
  buildContext,
  buildDietContext,
  loadSession,
  normalizeMessages
}
